ConVolution of Sobel Kernel over an Image

In [2]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

#1. Read an image I
I = cv2.imread("image.jpg")

#2. Convert into grayscale image Ig.
Ig = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)

#3. Extract a 3 x 3 matrix from Ig and name it as I
I = Ig[0:3, 0:3]
print(I)

#4. Do zero padding on I (3x3) -> Ip (5x5)
Ip = np.zeros((5, 5), dtype=Ig.dtype)
Ip[1:4, 1:4] = I
print("Zero-padded matrix Ip:")
print(Ip)

#5. Sx , Sy = Sobel Operators
Sx = np.array([[-1, 0, 1],
               [-2, 0, 2],
               [-1, 0, 1]], dtype=np.int32)
Sy = np.array([[-1, -2, -1],
               [ 0,  0,  0],
               [ 1,  2,  1]], dtype=np.int32)
print(Sx)
print(Sy)

#6. Convoluiton -> using for loops. [Ip (5x5) -> Ip (3x3) * Sx (3x3)]
Gx = np.zeros((3,3), dtype=np.int32)
Gy = np.zeros((3,3), dtype=np.int32)
for x in range(3):          # output rows
    for y in range(3):      # output cols
        sum_x = 0
        sum_y = 0
        for i in range(3):  # kernel rows
            for j in range(3):  # kernel cols
                sum_x += Ip[x+i, y+j] * Sx[i, j]
                sum_y += Ip[x+i, y+j] * Sy[i, j]
        Gx[x, y] = sum_x
        Gy[x, y] = sum_y

print("Gradient X (Gx):")
print(Gx)
print("Gradient Y (Gy):")
print(Gy)

#7. Gradient Magnitude
Magnitude = np.sqrt(Gx**2 + Gy**2)
Magnitude = Magnitude.astype(np.float32)
print("Gradient Magnitude:")
print(Magnitude)

#8. Gradient Orientation (in degrees)
Orientation = np.arctan2(Gy, Gx) * (180 / np.pi)
print("Gradient Orientation (degrees):")
print(Orientation)

#9. Edge Matrix (Threshold = Average of Magnitude values)
threshold = np.mean(Magnitude)
print("Threshold (Average of Magnitude matrix):", threshold)
Edge = np.zeros((3,3), dtype=np.uint8)
for i in range(3):
    for j in range(3):
        if Magnitude[i,j] >= threshold:
            Edge[i,j] = 1
        else:
            Edge[i,j] = 0
print("Final Edge Matrix:")
print(Edge)

[[251 251 251]
 [249 249 250]
 [246 247 248]]
Zero-padded matrix Ip:
[[  0   0   0   0   0]
 [  0 251 251 251   0]
 [  0 249 249 250   0]
 [  0 246 247 248   0]
 [  0   0   0   0   0]]
[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
[[-1 -2 -1]
 [ 0  0  0]
 [ 1  2  1]]
Gradient X (Gx):
[[ 751    1 -751]
 [ 996    4 -996]
 [ 743    5 -743]]
Gradient Y (Gy):
[[ 747  997  749]
 [ -14  -16  -10]
 [-747 -997 -749]]
Gradient Magnitude:
[[1059.2498    997.0005   1060.6611  ]
 [ 996.0984     16.492422  996.0502  ]
 [1053.5929    997.0125   1055.0118  ]]
Gradient Orientation (degrees):
[[  44.84700763   89.94253184  135.07639433]
 [  -0.80530933  -75.96375653 -179.4247605 ]
 [ -45.1538138   -89.71266149 -134.76958926]]
Threshold (Average of Magnitude matrix): 914.57446
Final Edge Matrix:
[[1 1 1]
 [1 0 1]
 [1 1 1]]
